---
title: '"Improving Time-Series Momentum Strategies: The Role of Trading Signals and Volatility Estimators"'
subtitle: "(draft)"
author: "Vito Lestingi"
date: "`r Sys.Date()`"
abstract: "This document includes replication material on some academic and practitioners' literature instrumental for our RGSoC 2020 project. The document itself is meant to be completely reproducible."
output:
  rmarkdown::pdf_document:
    citation_package: biblatex
bibliography: references.bib
vignette: >
  %\VignetteIndexEntry{"Improving Time-Series Momentum Strategies: The Role of Trading Signals and Volatility Estimators"}
  %\VignetteEngine{rmarkdown::render}
  %\VignetteEncoding{UTF-8}
---
  
```{r setup, include = FALSE}
knitr::opts_knit$set(
  root.dir = normalizePath('..')
)
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = TRUE,
  warning = FALSE,
  error = FALSE
)
```

# Introduction
These notes aim at reproducing \textcite{baltas-kosowski-2012}. The work has three fundamental aims:
first of all, to document empirical time-series momentum patterns, second to examine the information content of traditional and new signals to capture assets' momentum and third, to investigate a family of volatility estimators and assess their efficiency from a momentum investing point of view.

# Data and methodology
Data series we analyze are obtained from Bloomberg. For reproducibility purposes, we made efforts to re-create a data set as similar as possible to the one studied by \textcite{baltas-kosowski-2012}. Their data set consists of intra-day future prices of 12 classes of futures contracts, at a 30 minutes frequency. We analyze daily data on the same set of instruments. Next to the asset, for reference we also indicate Bloomberg tickers, class and the Exchange where the symbol considered is traded at. Futures contracts include: 6 commodities futures, among which Cocoa (`CC1`, Agricultural, ICE), Wheat (`W1`, Agricultural, CBOT), Crude Oil (`CL1`, Energy, CBOT), Natural Gas (`NG1`, Energy, Nymex), Copper (`HG1`, Industrial Metals, Comex), and Gold (`GC1`, Precious Metals, Comex); 2 equity indexes, S&P500 (`SPX`) and Eurostoxx50 (`SX5E`); 2 FX rates: US Dollar Index (`DX1`) and EUR/USD (`EC1`?); lastly, 2 interest rates: 3-month Eurodollar deposits (`ED1`) and 10-year US T-Note (`TY1`). 

Also, of methodological relevance is that futures quotes series are adjusted for rollovers so to limit attention to the most liquid contract, and series are aligned among the various exchanges where the contracts are traded in order to avoid the introduction of undue lead-lag effects in the analyses.

# Time-series Momentum Strategies
Time-series momentum is defined analogously to \textcite{moskowitz-ooi-pedersen-2012}. Generally, *univariate time-series momentum* is the trading rule that imposes to take a long/short position on a given asset depending on a metric of its past performance. The rule is completely identified by two parameters, namely the *lookback period* $J$ over which such performance is taken into account and the *holding period* $K$ during which the asset is effectively held in the portfolio. Since the same holds in principle for every tradable assets, time-series momentum can and is also be aggregated at portfolio level. Adopting \textcite{baltas-kosowski-2012} symbols and notation for readability purposes, such quantity is expressed as
$$
R^{\textrm{TS}}(t,t+K) = \sum_{i=1}^{M} X_{i}(t-J, t) \frac{10\% / \sqrt{M}}{\sigma_{i}(t,D)} R_{i}(t,t+K)
$$
where $M$ is the number of available assets, $X_{i}(t-J, t)$, $\sigma_{i}(t,D)$, and $\sqrt{M}$ is the scaling factor used in order to achieve a 10% ex-ante volatility.

The outline of subsections is as follows. First of all, in order to compute the above quantity we need a momentum signal and a volatility estimator. Each class of such elements shall receive individual treatment: many alternatives have consolidated in decades of research, each presents pros and cons by its own and in relation with the objectives of the particular study we aim to replicate.

## Volatility estimation
Traditional daily volatility estimators, like the standard deviation of daily past returns, provide relatively noisy volatility estimates. Authors study volatility estimators, the **realized variance** of \textcite{andersen-bollerslev-1998} and **volatility range estimators** including the estimators of \textcites{parkinson-1980, garman-klass-1980, rogers-satchell-1991, yang-zhang-2000}.

## Momentum signals
Authors empirically investigate and propose the following momentum signals: 

* **SIGN**, is the sign of the past return \textcite{moskowitz-ooi-pedersen-2012}, 
* **MA**, the moving average indicator.
* **EEMD**, related to the price trend that is extracted using the Ensemble Empirical Mode Decomposition.
* **TREND**, t-statistic of the slope coefficient from a least-squares fit of a linear trend on the asset price.
* **SMT**, more robust version of the previous signal using the statistically meaningful trend methodology.

### Returns predictability
Generally speaking, trading a given future contract or a portfolio based on momentum signals detailed above leads to more or less different returns streams. 
Following \textcite{baltas-kosowski-2012} we run time-series regression to assess the relationship between the signal and the returns generated by the strategy. The analysis is repeated at several horizons. In other words, we now quantitatively study what in these literature strains is informally referred to as signal's "predictive capability" or "predictive power".

## Time-series momentum strategies performance
In order to evaluate time-series momentum strategies performance, we examine the time-series return predictability using a pooled panel regression and a set of measures, namely the simple arithmetic average return, dollar growth, the Sharpe ratio and the (symmetric) downside-risk Sharpe ratio of \textcite{ziemba-2005}.
